### PR TITLE
update incorrect "required" attrs

### LINKED ISSUE #28: update to remove `required` portion for value
`document.cookie="foo=" sets a valueless cookie, so it is incorrect.

### PR DESCRIPTION
**Pull request by patrickkettner**
fixes #28

### CODE REVIEW

**Comment by patrickkettner** [comment]
@arronei this is failing with `FATAL ERROR: IDL ERROR LINE: 1 - Dictionary argument "cookie" without required members must be marked optional` ... why?

**Comment by arronei** [comment]
[Constructor(optional CookieInit cookie), Constructor(optional USVString cookie), Exposed=Window]

**Comment by patrickkettner** [comment]
@arronei that is throwing 
```
FATAL ERROR: Multiple local 'constructor' <dfn>s for 'Cookie' have the same linking text 'Cookie()'.
```

**Comment by arronei** [comment]
@patrickkettner its been awhile but try

[Constructor(optional (CookieInit or USVString) cookie), Exposed=Window]

**Pull request closed without merging**
